export const GET_ROOMS = 'GET_ROOMS';
export const SET_ACCOMMODATIONS = 'SET_ACCOMMODATIONS';
export const SET_ACCOMMODATION_AVAILIBILITY = 'SET_ACCOMMODATION_AVAILIBILITY';
export const ACCOMMODATION_LOADING = 'ACCOMMODATION_LOADING';
